# Generated by Django 3.1.7 on 2021-03-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_author_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AritcleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='articles_image')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aricles', to='core.article')),
            ],
        ),
    ]
